upload_max_filesize = 8M
post_max_size = 8M
max_execution_time = 30
max_input_time = 60
memory_limit = 256M
date.timezone = Asia/Jakarta

expose_php = Off
display_errors = Off
log_errors = On
error_log = /var/log/apache2/php_error.log